# Generated by Django 3.2.9 on 2021-11-22 11:21

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('profile_link', models.URLField(blank=True, help_text='Profile Link from Trading View', null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='International format, e.g: +44, +91, +234, etc..', max_length=128, null=True, region=None)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trading_strategy', models.CharField(max_length=150)),
                ('style', models.CharField(choices=[('HFT', 'HFT'), ('Intraday', 'Intraday'), ('Position', 'Position'), ('Scalp', 'Scalp'), ('Swing', 'Swing'), ('Scalp and swing', 'Scalp and swing'), ('Intraday and scalp', 'Intraday and scalp'), ('Intraday and swing', 'Intraday and swing'), ('Intraday, scalp and swing', 'Intraday, scalp and swing'), ('All', 'All')], max_length=30)),
                ('trading_with_firms', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Rather not say', 'Rather not say')], max_length=20)),
                ('risk_appetite', models.CharField(choices=[('Aggressive', 'Aggressive'), ('Low risk', 'Low risk'), ('Normal', 'Normal'), ('Rather not say', 'Rather not say')], max_length=20)),
                ('years_of_experience', models.CharField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
