# Generated by Django 3.2.9 on 2021-11-16 14:42

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingplan',
            name='firm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='firms.propfirm'),
        ),
        migrations.AlterField(
            model_name='accountsize',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=6),
        ),
        migrations.AlterField(
            model_name='accountsize',
            name='size',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='fundingplan',
            name='maximum_account_size',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10),
        ),
        migrations.AlterField(
            model_name='scalingplan',
            name='max_equity',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=10),
        ),
    ]
