# Generated by Django 3.2.9 on 2021-11-17 11:55

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0004_alter_cashrebate_expects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrebate',
            name='expects',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='USD', max_digits=6),
        ),
    ]
