# Generated by Django 3.2.9 on 2021-11-29 08:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0007_alter_firmcomparison_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmcomparison',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='firmA', unique=True),
        ),
    ]
