# Generated by Django 3.2.9 on 2021-11-29 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0008_alter_firmcomparison_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmcomparison',
            name='rules',
            field=models.SmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
