# Generated by Django 3.2.9 on 2021-12-04 17:55

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firms', '0011_firmsgeneralrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmsgeneralrating',
            name='name',
            field=models.CharField(default='FTMO', help_text='Not more than 10 characters.', max_length=10),
        ),
        migrations.CreateModel(
            name='GeneralRatingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abstract', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='abstract', unique=True)),
                ('note', ckeditor.fields.RichTextField(verbose_name='info')),
                ('date_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
