# Generated by Django 3.2.9 on 2021-12-04 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0013_alter_firmsgeneralrating_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmsgeneralrating',
            name='total_score',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
