# Generated by Django 3.2.9 on 2021-12-20 11:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0015_auto_20211220_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashrebate',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='auto'),
        ),
    ]
